# default_args is used to include configs from the _modular folder into this config. This ensures a modular way of combining different config files.
default_args: ["configs/_modular/sample_generation_NIBIO.yaml"]

############ modification of default args
sample_generation:
  search_radius_features: 2
  inner_edge: 8
  outer_edge: 13.5
  stride: 1

############ non-default args
forest_path: 'data_NIBIO/val/forest/merged_points.las' # path to forest point cloud for which validation tiles are to be generated
